"""baseline schema

Revision ID: 45195e752ddb
Revises: 
Create Date: 2026-07-10 20:24:38.233318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45195e752ddb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email_notify', sa.Boolean(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('feedback_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=True),
    sa.Column('positive_highlights', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('trend_analysis', sa.Text(), nullable=True),
    sa.Column('predictive_insights', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_insights_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_insight_owner_scope', ['user_id', 'scope'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('emotion', sa.String(length=32), nullable=False),
    sa.Column('emotion_score', sa.Float(), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index('ix_feedback_owner_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_emotion'), ['emotion'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_sentiment'), ['sentiment'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_service'), ['service'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_topic'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_service'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_sentiment'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_emotion'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_created_at'))
        batch_op.drop_index('ix_feedback_owner_created')

    op.drop_table('feedbacks')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_index('ix_insight_owner_scope')
        batch_op.drop_index(batch_op.f('ix_ai_insights_user_id'))

    op.drop_table('ai_insights')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    # ### end Alembic commands ###
